server.port=8081
spring.application.name=springboot-review
context.initializer.classes=com.asule.springbootreview.initializer.CInitializer
context.listener.classes=com.asule.springbootreview.listener.my.ThirdListener,com.asule.springbootreview.listener.my.FourthListener
isuper=asule


spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
