jdbc.url=jdbc:mysql://192.168.52.200:3306/big_market_01?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
jdbc.username=root
jdbc.password=Jszc@2026
jdbc.driverClassName=com.mysql.jdbc.Driver